---
trigger:
  - master
pr:
  - none
  
parameters:
  - name: Run_Stage
    displayName: Stage to Run
    type: string
    default: ALL
    values:
      - SBOX
      - DEV
      - TEST
      - STG
      - PROD
      - NONPROD
      - PRODUCTION
      - ALL



stages:
  - stage: SBOX
    condition: or(eq('${{ parameters.Run_Stage }}', 'SBOX'), contains('${{ parameters.Run_Stage }}', 'NONPROD'), contains('${{ parameters.Run_Stage }}', 'ALL'))
    jobs:
      - job: Success1
        steps:
        -  bash: |
            echo HelloWorld
      - job: Error
        dependsOn: Success1
        condition: eq(dependencies.Success1.result,'Succeeded') 
        steps:
        -  bash: |
            exit 1
      - job: Success2
        dependsOn: Error
        condition: eq(dependencies.Error.result, 'SucceededOrFailed')
        steps:
        -  bash: |
            echo HelloAgain

  - stage: DEV
    condition: or(eq('${{ parameters.Run_Stage }}', 'DEV'), contains('${{ parameters.Run_Stage }}', 'NONPROD'), contains('${{ parameters.Run_Stage }}', 'ALL'))
    jobs:
      - job: Development
        steps:
        -  bash: |
            echo DEV
  
  - stage: TEST
    condition: or(eq('${{ parameters.Run_Stage }}', 'TEST'), contains('${{ parameters.Run_Stage }}', 'NONPROD'), contains('${{ parameters.Run_Stage }}', 'ALL'))
    jobs:
      - job: Testing
        steps:
        -  bash: |
            echo TEST

  - stage: STG
    condition: and(or(eq('${{ parameters.Run_Stage }}', 'STG'), contains('${{ parameters.Run_Stage }}', 'PRODUCTION'), contains('${{ parameters.Run_Stage }}', 'ALL')), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    jobs:
      - job: Staging
        steps:
        -  bash: |
            echo STG

  - stage: PROD
    condition: and(or(eq('${{ parameters.Run_Stage }}', 'PROD'), contains('${{ parameters.Run_Stage }}', 'PRODUCTION'), contains('${{ parameters.Run_Stage }}', 'ALL')), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    jobs:
      - job: Production
        steps:
        -  bash: |
            echo PROD
