---
trigger:
  - master
pr:
  - none
  
parameters:
  - name: Run_Stage
    displayName: Stage to Run
    type: string
    default: ALL
    values:
      - SBOX
      - DEV
      - TEST
      - STG
      - PROD
      - NONPROD
      - PRODUCTION
      - ALL



stages:
  - stage: SBOX
    condition: or(eq('${{ parameters.Run_Stage }}', 'SBOX'), contains('${{ parameters.Run_Stage }}', 'NONPROD'), contains('${{ parameters.Run_Stage }}', 'ALL'))
    jobs:
      - job: Success1
        steps:
        -  bash: |
            echo HelloWorld
      - job: Error1
        dependsOn: Success1
        continueOnError: true
        condition: eq(dependencies.Success1.result,'Succeeded') 
        steps:
        -  bash: |
            exit 1
      - job: Success2
        dependsOn: Error1
        condition: eq(dependencies.Error1.result, 'SucceededWithIssues')
        steps:
        -  bash: |
            echo HelloAgain
      - job: Error2
        dependsOn: Success2
        continueOnError: true
        condition: eq(dependencies.Success2.result,'Succeeded') 
        steps:
        -  bash: |
            exit 1
        -  bash: |
            echo HelloOnceMore
           condition: succeededOrFailed()
      - job: Success3
        dependsOn: Error2
        condition: succeeded() # eq(dependencies.Error2.result, 'SucceededWithIssues')
        steps:
        -  bash: |
            echo Hello!

  - stage: DEV
    condition: or(succeeded(), eq('${{ parameters.Run_Stage }}', 'DEV'), contains('${{ parameters.Run_Stage }}', 'NONPROD'), contains('${{ parameters.Run_Stage }}', 'ALL'))
    jobs:
      - job: Development
        steps:
        -  bash: |
            echo DEV
  
  - stage: TEST
    condition: or(succeeded(), eq('${{ parameters.Run_Stage }}', 'TEST'), contains('${{ parameters.Run_Stage }}', 'NONPROD'), contains('${{ parameters.Run_Stage }}', 'ALL'))
    jobs:
      - job: Testing
        steps:
        -  bash: |
            echo TEST

  - stage: STG
    condition: and(succeeded('TEST'), or(eq('${{ parameters.Run_Stage }}', 'STG'), contains('${{ parameters.Run_Stage }}', 'PRODUCTION'), contains('${{ parameters.Run_Stage }}', 'ALL')), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
    jobs:
      - job: Staging
        steps:
        -  bash: |
            echo STG

  - stage: PROD
    condition: and(succeeded('STG'), or(eq('${{ parameters.Run_Stage }}', 'PROD'), contains('${{ parameters.Run_Stage }}', 'PRODUCTION'), contains('${{ parameters.Run_Stage }}', 'ALL')), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
    jobs:
      - job: Production
        steps:
        -  bash: |
            echo PROD
