---
trigger:
  - master
pr:
  - none

parameters:
  - name: Run_Stage
    displayName: Stage to Run
    type: string
    default: ALL
    values:
      - SBOX
      - DEV
      - TEST
      - STG
      - PROD
      - NONPROD
      - PRODUCTION
      - ALL



stages:
  - stage: SBOX
    condition: or(eq('${{ parameters.Run_Stage }}', 'SBOX'), contains('${{ parameters.Run_Stage }}', 'NONPROD'), contains('${{ parameters.Run_Stage }}', 'ALL'))
    jobs:
      - job: Sandbox
        steps:
        - task: AzurePowerShell@5
          inputs:
            azureSubscription: 'DTS-SHAREDSERVICES-SBOX'
            ScriptType: 'InlineScript'
            Inline: |
              Install-Module -Name Azure.Storage -RequiredVersion 4.6.0 -Force -Verbose
                   
              $blob = (Get-AzureRmStorageAccount -Name $(devopsStorageAccount) -ResourceGroupName $(devopsResourceGroup) | Get-AzureStorageBlob -Container "$(prefix)$(product)terraform" | Where-Object -Property Name -eq "$(prefix)$(product).tfstate")
              
              echo $blob
            azurePowerShellVersion: 'LatestVersion'